AppMVC/NicoApp/Controllers/PresupuestosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using NicoApp.Models;
using NicoApp.ViewModels;
using MVC.Interfaces;
using TiendaDB;
namespace NicoApp.Controllers;

public class PresupuestosController : Controller
{

    //private PresupuestosRepository presupuestosRepository;
    private IPresupuestoRepository _repo;
    private IProductoRepository _productoRepo;
    private IAuthenticationService _authService;

    public PresupuestosController(IPresupuestoRepository repo,
IProductoRepository prodRepo, IAuthenticationService authService)
    {
        _repo = repo;
        _productoRepo = prodRepo;
        _authService = authService;
    }

    public IActionResult Index()
    {

        // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso que necesite validar
        if (_authService.HasAccessLevel("Administrador") ||
            _authService.HasAccessLevel("Cliente") )
        {
        //si es es valido entra sino vuelve a login

            return View(_repo.getPresupuestos());
        }else
        {
            return RedirectToAction("Index", "Login");
        }
    }

    public IActionResult AccesoDenegado()
    {
        // El usuario está logueado, pero no tiene el rol suficiente.
        return View();
    }

    public IActionResult Create()
    {

        // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso
        if (!_authService.HasAccessLevel("Administrador"))
        {
            return RedirectToAction(nameof(AccesoDenegado));
        }
        //var producto = new Productos();
        var presupuestoNuevo = new PresupuestoViewModel
        {
            FechaCreacion = DateTime.Today
        };

        return View(presupuestoNuevo);
    }

    [HttpPost]
    public IActionResult Create(PresupuestoViewModel presupuestoVM)
    {
         // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso
        if (!_authService.HasAccessLevel("Administrador"))
        {
            return RedirectToAction(nameof(AccesoDenegado));
        }

        if (!ModelState.IsValid)
        {
            return View(presupuestoVM);
        }
        var nuevoPresupuesto = new Presupuestos
        {
            NombreDestinatario = presupuestoVM.NombreDestinatario,
            FechaCreacion1 = presupuestoVM.FechaCreacion
        };

        _repo.addNewPresupuesto(nuevoPresupuesto);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Edit(int idPresupuesto)
    {
         // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso
        if (!_authService.HasAccessLevel("Administrador"))
        {
            return RedirectToAction(nameof(AccesoDenegado));
        }

        var presupuesto = _repo.getPresupuestosById(idPresupuesto);

        var editPresupuestoVM = new PresupuestoViewModel
        {
            IdPresupuesto = presupuesto.IdPresupuesto,
            NombreDestinatario = presupuesto.NombreDestinatario,
            FechaCreacion = presupuesto.FechaCreacion1
        };

        return View(editPresupuestoVM);
    }

    [HttpPost]
    public IActionResult Edit(PresupuestoViewModel presupuestoVM)
    {
         // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso
        if (!_authService.HasAccessLevel("Administrador"))
        {
            return RedirectToAction(nameof(AccesoDenegado));
        }
        
        if (!ModelState.IsValid)
        {
            return View(presupuestoVM);
        }

        var presupuestoAEditar =  new Presupuestos
        {
            IdPresupuesto = presupuestoVM.IdPresupuesto,
            NombreDestinatario = presupuestoVM.NombreDestinatario,
            FechaCreacion1 = presupuestoVM.FechaCreacion
        };

        _repo.updatePresupuesto(presupuestoAEditar);

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int idPresupuesto)
    {
         // Comprobación de si está logueado
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }
        // Verifica Nivel de acceso
        if (!_authService.HasAccessLevel("Administrador"))
        {
            return RedirectToAction(nameof(AccesoDenegado));
        }
        _repo.deletePresupuesto(idPresupuesto);
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppMVC/NicoApp/Controllers/ProductosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NicoApp.Models;
using NicoApp.ViewModels;
using MVC.Interfaces;
using MVC.Services;
using TiendaDB;
namespace NicoApp.Controllers;

public class ProductosController : Controller
{

    //private ProductoRepository productoRepository;
    private IProductoRepository _repo;
    private IAuthenticationService _authService;
    public ProductosController(IProductoRepository prodRepo, IAuthenticationService authService)
    {
        //productoRepository = new ProductoRepository();
        _repo = prodRepo;
        _authService = authService;
    }
    [HttpGet]
    public IActionResult Index()
    {
        // Aplicamos el chequeo de seguridad
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        
        var listadoProductos = _repo.getProductos();
        return View(listadoProductos);
    }

    private IActionResult CheckAdminPermissions()
    {
    // 1. No logueado? -> vuelve al login
        if (!_authService.IsAuthenticated())
        {
        return RedirectToAction("Index", "Login");
        }

        // 2. No es Administrador? -> Da Error
        if (!_authService.HasAccessLevel("Administrador"))
        {
        // Llamamos a AccesoDenegado (llama a la vista correspondiente de Productos)
        return RedirectToAction(nameof(AccesoDenegado));
        }
        return null; // Permiso concedido
    }
    public IActionResult AccesoDenegado()
    {
        // El usuario está logueado, pero no tiene el rol suficiente.
        return View();
    }


    [HttpGet]
    public IActionResult Create()
    {
        //var producto = new Productos();
        return View(new ProductoViewModel());
    }

    [HttpPost]
    public IActionResult Create(ProductoViewModel productoVM)
    {

        // Aplicamos el chequeo de seguridad
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;

        if (!ModelState.IsValid)
        {
            return View(productoVM);
        }

        var nuevoProducto = new Productos
        {
            Descripcion = productoVM.Descripcion,
            Precio = productoVM.Precio
        };

        _repo.addNewProducto(nuevoProducto);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Edit(int idProducto)
    {

        // Aplicamos el chequeo de seguridad
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;

        var producto = _repo.getProductosById(idProducto);

        var editProductoVM = new ProductoViewModel
        {
            IdProducto = producto.IdProducto,
            Descripcion = producto.Descripcion,
            Precio = producto.Precio
        };

        return View(editProductoVM);
        //return View(producto);
    }

//
    [HttpPost]
    public IActionResult Edit(ProductoViewModel productoVM)
    {

        // Aplicamos el chequeo de seguridad
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;

        if (!ModelState.IsValid)
        {
            return View(productoVM);
        }

        var productoAEditar = new Productos
        {
            IdProducto = productoVM.IdProducto,
            Descripcion = productoVM.Descripcion,
            Precio = productoVM.Precio
        };

        _repo.updateProducto(productoAEditar.IdProducto,productoAEditar);
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Delete(int idProducto)
    {
        // Aplicamos el chequeo de seguridad
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;

        _repo.deleteProductoById(idProducto);
        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppMVC/NicoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NicoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NicoApp.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NicoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="Index">Presupuestos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NicoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>